events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    
    server {
        listen 80;
        server_name localhost;

        # Backend API
        location /api/ {
            proxy_pass http://host.docker.internal:5000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Backend OpenAPI
        location /docs {
            proxy_pass http://host.docker.internal:5000/docs;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Organization Portal
        location /org/ {
            proxy_pass http://host.docker.internal:5013/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Participle Portal
        location /participle/ {
            proxy_pass http://host.docker.internal:5014/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Frontend (Default)
        location / {
            proxy_pass http://host.docker.internal:5012/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
